global:
  marketplace-ami: false
  owner: howlee@amazon.com
  qsname: quickstart-sap-s4-hana
  regions:
    - ap-northeast-1
    - eu-west-1
    - us-east-1
    - us-west-1
  reporting: true
tests:
  sap-s4-new-vpc-t1:
    parameter_input: sap-s4hana-new.json
    template_file: sap-s4hana-new-vpc.template
  sap-s4-exg-vpc-t2:
    parameter_input: sap-s4hana-exg.json
    template_file: sap-s4hana-exg-vpc.template
  sap-s4-std-t3:
    parameter_input: sap-s4hana-std.json
    template_file: sap-s4hana-standard.template
